#!/bin/bash
set -euo pipefail

version="$(python -V)"
echo "${version}"

foo="bar" 
if [[ "$foo" =~ "bar" ]]; then
	echo "okay"
fi

if [[ "$version" =~ "Python 2.7.13" ]]; then
	echo "found it"
else
	echo "wrong version"
fi
