#!/bin/bash

## This is an example of batch job script for Karst HPC cluster at Indiana university

## We supply resources and time needed, path to code4Rice3K directory, and all arguments for the script we want to run:

#PBS -l nodes=1:ppn=8,walltime=04:00:00,vmem=20gb
#PBS -j oe
#PBS -m abe
#PBS -d /N/dc2/scratch/sialsaff/testing/code4Rice3K/
#PBS -F '-c bin/code4Rice3K.conf -b bamfiledir -r reference/ -i sample-1 -o output/ --nct 4 --nt 12' 

## Most HPC systems have their softwares installed as part of modules environment management system
## By loading different software packages, you can set and modify the programming environment as needed 
## Here we load Karst modules that are required for code4Rice3K workflow: 

module load java python samtools bcftools tabix vcftools raxml

## All is left is to run our script:

source bin/generatevcf
